### ISSUE TITLE
第一版需要简单修改的

### ISSUE THREAD

**Issue by ProkingDu** [chu-cs-lab/computer-maintain-order-app#29]
1. 商品box的优化：目前首页商品box的宽高是根据拉伸更改图片比例实现双列布局的，图片失去原本比例看起来很别扭。
2. 关键词修改：由于是商城模式的更改，需要将例如商品修改为服务、维修员修改为工程师、购买改为预约等，一方面是页面上文字的修改，可能还会有对应状态的映射需要修改。
3. 在下单（预约）时地址选择貌似存在一些问题，默认是从缓存中读取地址，但是我并没有添加地址这里就有了一个地址，且无法再添加新的。
4. 商品下单页面按照之前维修的逻辑更改，支付提示框的内容更改为预约提示框的内容，下单之后提示改为预约成功，等待工程师接单
5. 预约下单的时间段应该是必选的，并且在订单列表里面存在一个问题：如果没选择的话有一个undefined，如果选择一个仍然有一个undefined。
![小杜的个人图床](http://src.xiaodu0.com/2024/03/24/b8ceaccbcb3ef6826d560c08de86b6bd.png)
![小杜的个人图床](http://src.xiaodu0.com/2024/03/24/3656fb68fea4b34d0de377f20dea4c53.png)

暂时就这些。没有检查到别的问题。

**Comment by ProkingDu** [comment]
@awxiaoxian2020 PTAL!

**Comment by awxiaoxian2020** [comment]
我先来改文字
